TRUNCATE TABLE SITE_ID_LOAI_RAN; -- Delete all data
INSERT INTO SITE_ID_LOAI_RAN SELECT * FROM SITE_ID_LOAI_RAN_BACKUP;

TRUNCATE TABLE TRIEN_KHAI_THIET_BI; -- Delete all data
INSERT INTO TRIEN_KHAI_THIET_BI SELECT * FROM TRIEN_KHAI_THIET_BI_BACKUP;
